# Generated by Django 3.0.8 on 2020-07-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0003_user_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
